# this file will have labels for most of the other classes


class UserLabels:
	Email = "email"
	TimeStamp = "time_stamp"
	EmailConfirmationId = "email_confirmation_id"
	EmailConfirmed = "email_confirmed"
	Password = "password"
	PasswordConfirm = "password_confirm"
	AccountId = "account_id"
	Success = "success"
	Error = "error"
	UserInfo = "user_info"
	StripeCustomerId = "stripe_customer_id"
	Name = "name"
	User = "user"
	NewSettings = "new_settings"
	OldPassword = "old_password"

class ProductImageLabels:
	TimeStamp = "time_stamp"
	ImageId = "image_id"
	ProductId = "product_id"
	MainImage = "main_image"
	DeletedDate = "deleted_date"
	Images = "images"

class MarketProductLabels:
	TimeStamp = "time_stamp"
	ProuctId = "product_id"
	Success = "success"
	Error = "error"
	ProductId = "product_id"
	Manufacturer = "manufacturer"
	Price = "price"
	Brand = "brand"
	Description = "description"
	Category = "category"
	Rating = "rating"
	Name = "name"
	NumImages = "num_images"
	Images = "images"
	MainImage = "main_image"
	Inventory = "inventory"
	SoftDeleted = "soft_deleted"
	MarketProduct = "market_product"
	SaleEndDate = "sale_end_date"
	Tags = "tags"
	Product = "product"
	DateCreated = "date_created"
	ImageData = "image_data"

class ProductTagLabels:
	ProductId = "product_id"
	Tag = "tag"
	TimeStamp = "time_stamp"
	ProductTagId = "product_tag_id"

class FeedbackLabels:
	FeedbackId = "f_id"
	TimeStamp = "time_stamp"
	Email = "email"
	FeedbackContent = "feedback_content"
	Name = "name"
	Success = "success"
	AccountId = "account_id"

class RequestLabels:
	Success = "success"
	RequestId = "request_id"
	ConfirmationId = "confirmation_id"
	ImageData = "image_data"
	Description = "description"
	Email = "email"
	PriceRange = "price_range"
	Name = "name"
	PhoneNumber = "phone_number"
	DateCreated = "date_created"
	DateCompleted = "date_completed"
	Request = "request"

class PaymentLabels:
	StripeCustomerId = "stripe_customer_id"
	AccountId = "account_id"
	Success = "success"
	Error = "error"
	StripeId = "stripe_id"
	OrderId = "order_id"
	ProductId = "product_id"
	RefundDate = "refund_date"
	StripeChargeId = "stripe_charge_id"
	Id = "id"
	Product = "product"
	StripeToken = "stripeToken"
	Orders = "orders"


