# this file will have labels for most of the other classes

class DiscountLabels:
	DiscountId = "discount_id"

class EmailLabels:
	UnsubscribeId = "unsubscribe_id"
	EmailList = "email_list"
	NumSubscribers = "num_subscribers"
	SubscribedUsers = "subscribed_users"
	EmailListId = "email_list_id"
	NewEmailListName = "new_email_list_name"
	EmailListData = "email_list_data"
	Email = "email"
	EmailListName = "email_list_name"
	Unsubscribed = "unsubscribed"

class UserLabels:
	FbId = "fb_id"
	Id = "id"
	FirstName = "first_name"
	LastName = "last_name"
	FbResponse = "fb_response"
	MembershipTier = "membership_tier"
	GuestJwt = "guest_jwt"
	IsGuest = "is_guest"
	Order = "order"
	JwtDict = "jwt_dict"
	Type = "type"
	CartMessage = "cart_message"
	NumItems = "num_items"
	AdjustedItems = "adjusted_items"
	RecoveryPin = "recovery_pin"
	RecoveryPinExpiration = "recovery_pin_expiration"
	Email = "email"
	TimeStamp = "time_stamp"
	EmailConfirmationId = "email_confirmation_id"
	EmailConfirmed = "email_confirmed"
	Password = "password"
	PasswordConfirm = "password_confirm"
	AccountId = "account_id"
	Success = "success"
	Error = "error"
	UserInfo = "user_info"
	StripeCustomerId = "stripe_customer_id"
	Name = "name"
	User = "user"
	NewSettings = "new_settings"
	OldPassword = "old_password"
	Jwt = "jwt"
	Cards = "cards"
	Name = "name"
	AddressName = "address_name"
	AddressCity = "address_city"
	AddressCountry = "address_country"
	AddressLine1 = "address_line1"
	AddressLine2 = "address_line2"
	AddressZip = "address_zip"
	AddressState = "address_state"
	Cvc = "cvc"
	Number = "number"
	ExpMonth = "exp_month"
	ExpYear = "exp_year"
	Addresses = "addresses"
	Description = "description"
	AddressId = "address_id"
	StripeCardId = "stripe_card_id"
	Orders = "orders"
	CartSize = "cart_size"
	AddressId = "address_id"
	CardId = "card_id"
	IsAdmin = "is_admin"
	Cart = "cart"
	DefaultCard = "default_card"
	DefaultAddress = "default_address"
	


class ProductImageLabels:
	TimeStamp = "time_stamp"
	ImageId = "image_id"
	ProductId = "product_id"
	MainImage = "main_image"
	DeletedDate = "deleted_date"
	Images = "images"
	ImageText = "image_text"
	Live = "live"

class MarketProductLabels:
	RelatedProductTags = "related_product_tags"
	ProductSearchTags = "product_search_tags"
	ProductListingTags = "product_listing_tags"
	SaleTextHome = "sale_text_home"
	SaleTextProduct = "sale_text_product"
	Tag = "tag"
	Quadrant1 = "quadrant1"
	Quadrant2 = "quadrant2"
	Quadrant3 = "quadrant3"
	Quadrant4 = "quadrant4"
	MoreDetails = "more_details"
	ManufacturerFee = "manufacturer_fee"
	ManufacturerEmail = 'manufacturer_email'
	SaleText = "sale_text"
	ShowManufacturerLogo = "show_manufacturer_logo"
	ManufacturerLogoId = "manufacturer_logo_id"
	SecondTabName = "second_tab_name"
	SecondTabText = "second_tab_text"
	ImageText = "image_text"
	LiveStatus = "live_status"
	User = "user"
	Password = "password"
	Username = "username"
	TimeStamp = "time_stamp"
	ProuctId = "product_id"
	Success = "success"
	Error = "error"
	ProductId = "product_id"
	Manufacturer = "manufacturer"
	Price = "price"
	Brand = "brand"
	Description = "description"
	Category = "category"
	Rating = "rating"
	Name = "name"
	NumImages = "num_images"
	Images = "images"
	MainImage = "main_image"
	Inventory = "inventory"
	SoftDeleted = "soft_deleted"
	MarketProduct = "market_product"
	SaleEndDate = "sale_end_date"
	Tags = "tags"
	Product = "product"
	DateCreated = "date_created"
	ImageData = "image_data"
	ImageId = "image_id"
	Jwt = "jwt"
	ProductTemplate = "product_template"
	NumItemsLimit = "num_items_limit"
	Active = "active"
	Color = "color"
	Size = "size"
	HasVariants = "has_variants"
	VariantId = "variant_id"
	Type = ""
	Variants = "variants"
	Variant = "variant"
	VariantType = "variant_type"
	VariantTypes = "variant_types"
	NewVariantType = "new_variant_type"
	ProductIdList = "product_id_list"
	Products = "products"
	Live = "live"
	VariantTypeDescription = "variant_type_description"
	Username = "username"

class ProductTagLabels:
	ProductId = "product_id"
	Tag = "tag"
	TimeStamp = "time_stamp"
	ProductTagId = "product_tag_id"
	Jwt = "jwt"

class FeedbackLabels:
	FeedbackId = "f_id"
	TimeStamp = "time_stamp"
	Email = "email"
	FeedbackContent = "feedback_content"
	Name = "name"
	Success = "success"
	AccountId = "account_id"
	Message = "message"
	Category = "category"
	OrderId = "order_id"

class RequestLabels:
	Success = "success"
	RequestId = "request_id"
	ConfirmationId = "confirmation_id"
	ImageData = "image_data"
	Description = "description"
	Email = "email"
	PriceRange = "price_range"
	Name = "name"
	PhoneNumber = "phone_number"
	DateCreated = "date_created"
	DateCompleted = "date_completed"
	Request = "request"
	Confirmed = "confirmed"
	Completed = "completed"
	Jwt = "jwt"

class PaymentLabels:
	Discounts = "discounts"
	Inventory = "inventory"
	Error = "error"
	CartItem = "cart_item"
	Name = "name"
	Jwt = "jwt"
	StripeCustomerId = "stripe_customer_id"
	AccountId = "account_id"
	Success = "success"
	Error = "error"
	StripeId = "stripe_id"
	OrderId = "order_id"
	ProductId = "product_id"
	RefundDate = "refund_date"
	StripeChargeId = "stripe_charge_id"
	Id = "id"
	Product = "product"
	StripeToken = "stripeToken"
	Orders = "orders"
	LobAddressId = "lob_address_id"
	TotalPrice = "total_price"
	Product = "product"
	Address = "address"
	AddressName = "address_name"
	AddressDescription = "addresss_description"
	AddressCity = "address_city"
	AddressCountry = "address_country"
	AddressLine1 = "address_line1"
	AddressLine2 = "address_line2"
	AddressZip = "address_zip"
	AddressState = "address_state"
	NumItems = "num_items"
	Price = "price"
	DateCreated = "date_created"
	Card = "card"
	VariantId = "variant_id"
	MainImage = "main_image"
	CardBrand = "card_brand"
	CardLast4 = "card_last4"
	Source = "source"
	Last4 = "last4"
	Brand = "brand"
	OrderShipping = "order_shipping"
	ItemsPrice = "items_price"
	TotalPrice = "total_price"
	Items = "items"
	SalesTaxPrice = "sales_tax_price"


class CartLabels:
	ShippingDiscount = "shipping_discount"
	Discounts = "discounts"
	ItemsDiscount = "items_discount"
	OriginalShippingPrice = "original_shipping_price"
	OriginalItemsPrice = "original_items_price"
	DiscountMessage = "discount_message"
	DiscountedCartPrice = "discounted_cart_price"
	MembershipTier = "membership_tier"
	ManufacturerEmail = "manufacturer_email"
	ManufacturerFee = "manufacturer_fee"
	JwtDict = "jwt_dict"
	Order = "order"
	Type = "type"
	SalesTaxPrice = "sales_tax_price"
	Address = "address"
	Inventory = "inventory"
	StripeCustomerId = "stripe_customer_id"
	AccountId = "account_id"
	Success = "success"
	Error = "error"
	StripeId = "stripe_id"
	OrderId = "order_id"
	ProductId = "product_id"
	Id = "id"
	Product = "product"
	StripeToken = "stripeToken"
	Jwt = "jwt"
	NumItems = "num_items"
	CartId = "cart_id"
	Cart = "cart"
	Items = "items"
	Price = "price"
	Addresses  = "addresses"
	Cards = "cards"
	CardId = "card_id"
	AddressId = "address_id"
	Name = "name"
	Description = "description"
	AddressCity = "address_city"
	AddressCountry = "address_country"
	AddressLine1 = "address_line1"
	AddressLine2 = "address_line2"
	AddressZip = "address_zip"
	AddressState = "address_state"
	NewNumItems = "new_num_items"
	Quantity = "quantity"
	NumItemsLimit = "num_items_limit"
	Orders = "orders"
	MainImage = "main_image"
	User = "user"
	VariantId = "variant_id"
	CartItem = "cart_item"
	VariantType = "variant_type"
	Variant = "variant"
	TotalPrice = "total_price"
	ShippingPrice = "shipping_price"
	ItemsPrice = "items_price"
	Message = "message"

class AddressLabels:
	AddressId = "address_id"
	AccountId = "account_id"
	Name = "name"
	AddressCity = "address_city"
	AddressCountry = "address_country"
	AddressLine1 = "address_line1"
	AddressLine1 = "address_line2"
	AddressZip = "address_zip"
	AddressState = "address_state"
	Jwt = "jwt"

class SearchLabels:
	SearchInput = "search_input"
	Product = "product"
	Products = "products"


class ErrorLabels:
	Database = "database"
	Charge = "charge"
	Email = "email"


class AdminLabels:
	ErrorMessage = "error_message"
	Ip = "ip"
	Username = "username"
	AttemptId = "attempt_id"
	Success = "success"
	DateCreated = "date_created"
	IsAdmin = "is_admin"
	Password = "password"
	Name = "name"
	User = "user"
	Jwt = "jwt"
	AdminActionId = "admin_action_id"
	RequestPath = "request_path"


