# this file will have labels for most of the other classes


class UserLabels:
	Email = "email"
	TimeStamp = "time_stamp"
	EmailConfirmationId = "email_confirmation_id"
	EmailConfirmed = "email_confirmed"
	Password = "password"
	PasswordConfirm = "password_confirm"
	AccountId = "account_id"
	Success = "success"
	Error = "error"
	UserInfo = "user_info"
	StripeCustomerId = "stripe_customer_id"
	Name = "name"
	User = "user"
	NewSettings = "new_settings"
	OldPassword = "old_password"
	Jwt = "jwt"
	Cards = "cards"
	Name = "name"
	AddressName = "address_name"
	AddressCity = "address_city"
	AddressCountry = "address_country"
	AddressLine1 = "address_line1"
	AddressLine2 = "address_line2"
	AddressZip = "address_zip"
	AddressState = "address_state"
	Cvc = "cvc"
	Number = "number"
	ExpMonth = "exp_month"
	ExpYear = "exp_year"
	Addresses = "addresses"
	Description = "description"
	AddressId = "address_id"
	StripeCardId = "stripe_card_id"
	Orders = "orders"


class ProductImageLabels:
	TimeStamp = "time_stamp"
	ImageId = "image_id"
	ProductId = "product_id"
	MainImage = "main_image"
	DeletedDate = "deleted_date"
	Images = "images"

class MarketProductLabels:
	TimeStamp = "time_stamp"
	ProuctId = "product_id"
	Success = "success"
	Error = "error"
	ProductId = "product_id"
	Manufacturer = "manufacturer"
	Price = "price"
	Brand = "brand"
	Description = "description"
	Category = "category"
	Rating = "rating"
	Name = "name"
	NumImages = "num_images"
	Images = "images"
	MainImage = "main_image"
	Inventory = "inventory"
	SoftDeleted = "soft_deleted"
	MarketProduct = "market_product"
	SaleEndDate = "sale_end_date"
	Tags = "tags"
	Product = "product"
	DateCreated = "date_created"
	ImageData = "image_data"
	ImageId = "image_id"
	Jwt = "jwt"
	StoryImageId = "story_image_id"
	StoryText = "story_text"

class ProductTagLabels:
	ProductId = "product_id"
	Tag = "tag"
	TimeStamp = "time_stamp"
	ProductTagId = "product_tag_id"
	Jwt = "jwt"

class FeedbackLabels:
	FeedbackId = "f_id"
	TimeStamp = "time_stamp"
	Email = "email"
	FeedbackContent = "feedback_content"
	Name = "name"
	Success = "success"
	AccountId = "account_id"

class RequestLabels:
	Success = "success"
	RequestId = "request_id"
	ConfirmationId = "confirmation_id"
	ImageData = "image_data"
	Description = "description"
	Email = "email"
	PriceRange = "price_range"
	Name = "name"
	PhoneNumber = "phone_number"
	DateCreated = "date_created"
	DateCompleted = "date_completed"
	Request = "request"
	Confirmed = "confirmed"
	Completed = "completed"
	Jwt = "jwt"

class PaymentLabels:
	Jwt = "jwt"
	StripeCustomerId = "stripe_customer_id"
	AccountId = "account_id"
	Success = "success"
	Error = "error"
	StripeId = "stripe_id"
	OrderId = "order_id"
	ProductId = "product_id"
	RefundDate = "refund_date"
	StripeChargeId = "stripe_charge_id"
	Id = "id"
	Product = "product"
	StripeToken = "stripeToken"
	Orders = "orders"
	LobAddressId = "lob_address_id"
	TotalPrice = "total_price"
	Product = "product"
	Address = "address"
	AddressName = "address_name"
	AddressDescription = "addresss_description"
	AddressCity = "address_city"
	AddressCountry = "address_country"
	AddressLine1 = "address_line1"
	AddressLine2 = "address_line2"
	AddressZip = "address_zip"
	AddressState = "address_state"
	NumItems = "num_items"
	Price = "price"
	DateCreated = "date_created"
	Card = "card"


class CartLabels:
	StripeCustomerId = "stripe_customer_id"
	AccountId = "account_id"
	Success = "success"
	Error = "error"
	StripeId = "stripe_id"
	OrderId = "order_id"
	ProductId = "product_id"
	Id = "id"
	Product = "product"
	StripeToken = "stripeToken"
	Jwt = "jwt"
	NumItems = "num_items"
	CartId = "cart_id"
	Cart = "cart"
	Items = "items"
	Price = "price"
	Addresses  = "addresses"
	Cards = "cards"
	CardId = "card_id"
	AddressId = "address_id"
	Name = "name"
	Description = "description"
	AddressCity = "address_city"
	AddressCountry = "address_country"
	AddressLine1 = "address_line1"
	AddressLine2 = "address_line2"
	AddressZip = "address_zip"
	AddressState = "address_state"
	NewNumItems = "new_num_items"
	Quantity = "quantity"
	NumItemsLimit = "num_items_limit"
	Orders = "orders"
	MainImage = "main_image"

class AddressLabels:
	AddressId = "address_id"
	AccountId = "account_id"
	Name = "name"
	AddressCity = "address_city"
	AddressCountry = "address_country"
	AddressLine1 = "address_line1"
	AddressLine1 = "address_line2"
	AddressZip = "address_zip"
	AddressState = "address_state"
	Jwt = "jwt"



